default: &default
  adapter: postgresql
  encoding: unicode  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: E37imp#8
  host: localhost
  port: 5432

development:
  <<: *default
  database: test-guru_development

test:
  <<: *default
  database: test-guru_test

production:
  <<: *default
  database: test-guru_production
  # url: <%= ENV['DATABASE_URL'] %>
  # database: mysite_production
  # username: mysite
  # password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>