default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['LOCAL_DATABASE_USERNAME'] %>
  password: <%= ENV['LOCAL_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432
  


development:
  <<: *default
  database: test-guru_development
 
test:
  <<: *default
  database: test-guru_test

production:
  <<: *default
  database: test-guru_production
  host: <%= ENV['PRODUCTION_HOST_NAME'] %>
  url: <%= ENV['PRODUCTION_DATABASE_URL'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
